sudo: false
language: node_js
node_js:
  - v5
  - v4
services: mongodb

before_script:

  - mongo test --eval 'db.users.insert({"username":"admin","role": "admin","email"  :"admin@email.com","password":"jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg="});'

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage