language: python
python:
  - "2.7"

# command to install dependencies
install:
  - bin/install
  - pip install coveralls

# command to run tests
script:
  - bin/test

# command to run coverage
after_success:
  coveralls